create table if not exists public.catalog_playback_events (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  session_id text not null,
  user_id uuid null,
  playable_type text not null,
  playable_id uuid not null,
  title_id uuid null references public.catalog_titles(id) on delete set null,
  channel_id uuid null references public.channels(id) on delete set null,
  event_type text not null,
  device_type text null,
  platform text null default 'web',
  os text null,
  country text null,
  position_sec integer null,
  duration_sec integer null,
  created_at timestamptz not null default now()
);

create index if not exists catalog_playback_events_tenant_created_at_idx
  on public.catalog_playback_events (tenant_id, created_at desc);

create index if not exists catalog_playback_events_tenant_playable_created_idx
  on public.catalog_playback_events (tenant_id, playable_type, playable_id, created_at desc);

create index if not exists catalog_playback_events_tenant_session_created_idx
  on public.catalog_playback_events (tenant_id, session_id, created_at desc);

create index if not exists catalog_playback_events_tenant_event_created_idx
  on public.catalog_playback_events (tenant_id, event_type, created_at desc);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'catalog_playback_events_playable_type_check'
  ) then
    alter table public.catalog_playback_events
      add constraint catalog_playback_events_playable_type_check
      check (playable_type in ('movie', 'episode', 'replay'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'catalog_playback_events_position_sec_check'
  ) then
    alter table public.catalog_playback_events
      add constraint catalog_playback_events_position_sec_check
      check (position_sec is null or position_sec >= 0);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'catalog_playback_events_duration_sec_check'
  ) then
    alter table public.catalog_playback_events
      add constraint catalog_playback_events_duration_sec_check
      check (duration_sec is null or duration_sec > 0);
  end if;
end $$;

alter table public.catalog_playback_events enable row level security;

drop policy if exists catalog_playback_events_read_scoped on public.catalog_playback_events;
create policy catalog_playback_events_read_scoped
on public.catalog_playback_events
for select
using (public.is_oniix_admin() or public.has_tenant_membership(tenant_id));

revoke insert, update, delete on public.catalog_playback_events from anon, authenticated;
